# Generated by Django 3.2 on 2023-09-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.TextField(default='TvAnRzGJlHSb'),
        ),
    ]
